### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [saldl/saldl#2]
Would you like to add more error handling for return values from functions like the following?
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html) ⇒ [sal_dl](https://github.com/saldl/saldl/blob/c79109e563c3da72b68cf495847abdfd5351d8e3/src/saldl.c#L97)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [valid_filename](https://github.com/saldl/saldl/blob/2ca2c93a2bbbfb7556c336e84ff419b09c79fb68/src/common.c#L228)

**Comment by elfring** [comment]
Are there any [more update candidates](https://github.com/saldl/saldl/blob/ed22bfb0bd14237009b2394dbb7336408f0c2f63/src/common.c#L186) left over?

**Comment by MoSal** [comment]
fputs_count() only writes to stderr.
There are no checks for any function that writes to stderr ATM.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.
Would you like to detect every error situation as early as possible?

**Comment by MoSal** [comment]
I didn't say I'm going to ignore this.

I just wanted to assure you (and whoever else reading this) that this function
is not used to write to regular files, and won't corrupt anyone's data if it fails
for some reason.

BTW, how does one communicate ..writing to stderr failures.. to the user? 😉

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B) also for your software?

How many information would you like to express by [the exit status of your program](https://en.wikipedia.org/wiki/Exit_status)?

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by MoSal** [comment]
saldl should either succeed, or fail with a hopefully descriptive fatal message.
I don't see the need for other exit statuses.

**Comment by elfring** [comment]
An exit code which will be different from a boolean value can give a bit more information if the run-time system was unable to generate a meaningful error message, can't it?

**Comment by MoSal** [comment]
If we are talking about non-interactive use. I think this should be a better and more informative solution than hunting for exit code meanings (coupled with a check for success/fail of course):

```
saldl ARGS -VVV --no-status 2>>some_log_file
```

**Comment by elfring** [comment]
Will any dedicated exit code help to indicate a specific error situation if output files which should be stored in a place that [became full](https://en.wikipedia.org/wiki//dev/full) will be passed to the program?

**Comment by MoSal** [comment]
I stress-tested this today.

`fwrite()` and `fread()` checks are good. But not checking `fflush()`'s return value was a big
mistake on my part (now fixed).

I still think those detailed messages are more helpful than a return code with some abstract meaning:

`[fatal] merge_finished_mem: Write to file failed at offset 1048576: No space left on device`

`[fatal] file_write_function: Writing 16384 bytes to file some_file.tmp.sal/0 failed: No space left on device`

`[fatal] file_write_function: Writing 16384 bytes to file some_file.part.sal failed: No space left on device`

**Comment by elfring** [comment]
Such messages can help if you can write to and read them from the error output channel at all.

**Comment by MoSal** [comment]
I might give "writing to stderr errors" a special exit code when I start
checking for them. But I'm not sure it's going to be very useful!

Both Bash and ZSH will produce an error with:

```
echo bla >>/dev/full
```

But will succeed happily with:

```
saldl --version 2>>/dev/full
saldl --version >>/dev/full 2>&1
```

Only this will produce an error:

```
saldl --version 2>&1 | tee >>/dev/full
```

I wouldn't expect users to know this subtle trick.

As we depend on the shell for saving logs. Anything I do will only be useful in
highly-unlikely situations. While this shell behavior will remain unfixable (by me).

**Comment by elfring** [comment]
The exception handling is still incomplete in this software.

More places for further considerations:
- fclose
- fputc
- fputs
- fseek
- signal

**Comment by MoSal** [comment]
> The exception handling is still incomplete in this software.
> 
> More places for further considerations:
> - fclose
> - fputc
> - fputs
> - fseek
> - signal

All done.
