### ISSUE TITLE
Support for input file

### ISSUE THREAD

**Issue by ghost** [saldl/saldl#9]
I looked the documentation, but didn't find option to input list of urls. Am I missing something?

**Comment by MoSal** [comment]
I don't know how I didn't see this earlier, sorry.

This can be trivially done via scripting. So I consider it out of scope.

This can be done in `bash` or `zsh`:

``` bash
cat URLs.txt | while read u; do
  saldl "$u"
done
```

The above can be wrapped in a shell function:

``` bash
function saldl_i() {
  i_file="$1"
  shift
  cat "$i_file" | while read u; do
    saldl $@ "$u"
  done
}
```
The body of the function can also be stored in a stand-alone script:

``` bash
#!/bin/bash

# the body of the function here
```

And now one can call `saldl_i <input_fiile> [saldl_arguments]`.

**Comment by ghost** [comment]
Thanks.
Do you have plans to implement it as an argument in saldl?

**Comment by MoSal** [comment]
No.

As I wrote earlier. This can be trivially done via scripting. So I consider it out of scope for `saldl`.
